// <auto-generated />
namespace OneToManyApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class v1onetomanyadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v1onetomanyadded));
        
        string IMigrationMetadata.Id
        {
            get { return "202001240621030_v1-onetomanyadded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
